name: Build And Test

on:
  workflow_dispatch:
  push:
  pull_request: # do not use pull_request_target since it probably won't up to date with PR
    types:
      - opened
      - synchronize

concurrency:
  group: build-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle Check
        run: ./gradlew check
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: LOG-METADATA-1
        run: |
          function output() {
            echo "output:$1=$2"
          }
          output PR_NUMBER "${{ github.event.number }}"
          output HEAD_SHA "${{ github.sha }}"
      - name: Gradle Build
        run: ./gradlew build "-Dmod_artifact_suffix=-pr${{ github.event.number }}-$(git rev-parse --short ${{ github.sha }})"
      - name: Rename build Artifact
        run: mv build/reobfJar/output.jar build/reobfJar/starlance-production-mapped.jar
      - name: Upload Build Artifacts
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('Starlance Artifacts PR {0}', github.event.number) }}
          path: |
            build/libs
            build/reobfJar
          overwrite: true
          if-no-files-found: error
      - name: LOG-METADATA-2
        run: |
          function output() {
            echo "output:$1=$2"
          }
          output ARTIFACT_ID "${{ steps.artifact.outputs.artifact-id }}"
          output ARTIFACT_URL "${{ steps.artifact.outputs.artifact-url }}"
